### PR TITLE
Add/Remove Methods

### PR DESCRIPTION
**Pull request by corinwagen**
This change should be synced to the upcoming PRs in Peregrine (Psi4 release and the xTB upgrade). 

## Add Methods
- r2SCAN-3c
- wB97X-3c
- wB97-MD3BJ
- DSD-BLYP-D3BJ (!)
- GFN-FF

## Rename Methods
- TPSS0 => TPSSh

## Remove Methods
- LSDA
- BLYP
- BP86
- B97-D3
- B3PW91
- B97M-V
- wB97X-D
- AIMNet2 B97-3C

All of these methods should now be in Psi4 at a minimum. I need to figure out which are in Terachem and PySCF still, and store this somewhere for Ari to ingest. Psi4 should become the "default" choice though, I think, since it supports everything here natively.

This will be a good change, but is somewhat annoying to deal with. We'll need to make sure that the front-end handles "old" methods gracefully for a little while, at least, although I doubt there are very many floating around...?

**Not Included In This PR** - figuring out a better way to store and handle methods, basis sets, and engines. I know that this has been requested but it is a large task and I have done more refactoring this week than I'm happy with for a pre-revenue company. 

My hope is to get this all sorted out soon, maybe EOD tomorrow. I am tired of this engineering crap.

### CODE REVIEW

**Comment by corinwagen** [comment]
Also here - trying to move towards `camel_case` for all enums, and modifying stjames.LowercaseStringEnum to ensure back-compatibility.

**Comment by ariwagen** [comment]
Sharing my code.

Here's what I'm looking at. Questions: 
  - in PySCF: 
      - should I add `tpssh`?
  - TeraChem:
      - why are we removing `b97-d3`? if you want GPU-accelerated DFT, this seemed like a good choice to me. i'm assuming Psi4 doesn't approach TeraChem speed
  - xTB:
      - want me to list `GFN-FF`?
      - should I remove `GFN1-xTB`?
      
Here's what, as of right now, I have available for submission:

```javascript
export const AIMNet2Methods: MethodsDict = {
  "aimnet2_wb97md3": {},
};

export const xTBMethods: MethodsDict = {
  "gfn_ff": {},
  //"gfn0_xtb": {},
  "gfn1_xtb": {},
  "gfn2_xtb": {},
};

export const PySCFMethods: MethodsDict = {
  "hf": {},
  "pbe": {},
  "r2scan": {},
  "tpss": {},
  "m06l": {},
  "pbe0": {},
  "b3lyp": {},
  "m06": {},
  "m062x": {},
  "camb3lyp": {},
  "wb97x_v": {},
  "wb97m_v": {},
  /*"lsda": {},
  "blyp": {},
  "bp86": {},
  "b97-d3": {
    require_corrections: ["d3bj"],
  },
  "b3pw91": {},
  "b97m_v": {},
  "tpss0": {},*/
};

export const TeraChemMethods: MethodsDict = {
  "hf": {},
  "lsda": {},
  "pbe": {},
  "pbe0": {},
  "b3lyp": {},
  "camb3lyp": {},
  "wb97x_d3": {
    require_corrections: ["d3"],
  },
  /*"blyp": {},
  "b97-d3": {
    require_corrections: ["d3"],
  },
  "b3pw91": {},*/
};
```

**Comment by ariwagen** [comment]
Also just to say it ... `camel_case` is not in camel case. Pretty sure that's `snake_case.`

**Comment by jevandezande** [comment]
You can enable [PEP-8 Naming Checks](https://docs.astral.sh/ruff/rules/#pep8-naming-n) (`ruff check --select N`). It will yell at you about various conventions that we flout since we are chemists (e.g. `pKaMicrostate` is not CamelCase and `deltaG` is not ssssssnake_case), and so it may not be worth enabling globally, but it can provide a quick check.

**Comment by jevandezande** [comment]
I don't see the point of including GFN1-xTB. There are minor corner cases where it might be marginally better than GFN2, but I'd actually prefer GFN0 over it, since GFN0 skips the SCF, allowing for optimizations steps where GFN{1,2} would fail to converge the SCF.

GFN-FF is a generally applicable force-field, and thus much faster but significantly less accurate than GFN2. We use it in conformational search, so it might be good to make it available for general computations so that customers can quickly run frequencies on a selected conformer. Could there be any product positioning reasons to avoid adding it, if we plan to release an MLFF?

**Comment by corinwagen** [comment]
@jevandezande I don't think GFN-FF is bad at all. Happy to remove GFN1-xTB from the front-end but AFAIK we still want it around in the backend, because [we can't get CM5 charges with GFN2-xTB](https://github.com/grimme-lab/xtb/issues/1050).

**Comment by corinwagen** [comment]
> * why are we removing `b97-d3`? if you want GPU-accelerated DFT, this seemed like a good choice to me. i'm assuming Psi4 doesn't approach TeraChem speed

Yes, but TeraChem can handle range separation, so wb97x-d3 is best IIRC. Here's what [TeraChem 1.9](http://www.petachem.com/doc/userguide.pdf) can do:

```
Restricted wavefunction:
rhf | svwn | bhandhlyp | blyp | b3lyp |b3lyp1 | b3lyp5 |
b3p86 | b3pw91 | pbe | pw91 | revpbe | pbe0 | revpbe0 | wpbe
| wpbeh | bop | mubop | camb3lyp | b97 | wb97 | wb97x
b3lyp or b3lyp1: VWN1 correlation (B3LYP in Gaussian)
b3lyp5: VWN5 correlation (B3LYP in GAMESS)
```

**Pull request merged**
